version: '3'
services:

  serverless:
    build: ./serverless
    environment:
      - DB=mongodb://db:27017/
    ports:
      - "3000:3000"

  db:
    image: mongo
    ports:
    - "27027:27017"

  game:
    build: ./game
    environment:
     - DB=mongodb://db:27017/
     - SERVERLESS_URL=http://192.168.99.100:3000/
    ports:
      - "3003:3000"

  interface:
    build: ./interface
    environment:
      - SERVERLESS_URL=http://192.168.99.100:3000/
    ports:
      - "4200:4200"
